### ISSUE TITLE
mapview values of raster are not shown on hover

### ISSUE THREAD

**Issue by DavZim** [r-spatial/mapview#481]
When I use the example code:
```
library(raster)
library(mapview)

kili_data <- system.file("extdata", "kiliNDVI.tif", package = "mapview")
kiliNDVI <- raster::stack(kili_data)

## view the first 3 layers
mapview(kiliNDVI[[1:3]])
```
I see this, which does not contain any hover information

![image](https://github.com/r-spatial/mapview/assets/15910496/82bad359-3bee-40fe-923e-44f5d9b7c065)

at the same time I see the following errors in the javascript console
```
leafem: Failed to find window.data
joda.js:131 Uncaught TypeError: layer.value.toFixed is not a function
    at rasterPicker.renderInfo (joda.js:131:90)
    at rasterPicker.pick (joda.js:52:33)
    at e.<anonymous> (addImageQuery-bindings.js:32:20)
    at e.fire (leaflet.js:5:16621)
    at e._fireDOMEvent (leaflet.js:5:44344)
    at e._handleDOMEvent (leaflet.js:5:43661)
    at HTMLDivElement.r (leaflet.js:5:5993)
```

My session info is
```
> sessionInfo()
R version 4.3.1 (2023-06-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Etc/UTC
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
[1] mapview_2.11.2 raster_3.6-26  sp_2.1-4      

loaded via a namespace (and not attached):
 [1] jsonlite_1.8.8          compiler_4.3.1          renv_0.15.5            
 [4] Rcpp_1.0.12             leaflet_2.2.2           jquerylib_0.1.4        
 [7] scales_1.3.0            png_0.1-8               fastmap_1.1.1          
[10] lattice_0.21-8          R6_2.5.1                classInt_0.4-10        
[13] satellite_1.0.5         sf_1.0-16               htmlwidgets_1.6.4      
[16] leaflet.providers_2.0.0 units_0.8-5             munsell_0.5.1          
[19] DBI_1.2.2               rlang_1.1.3             terra_1.7-71           
[22] xfun_0.43               cli_3.6.2               magrittr_2.0.3         
[25] class_7.3-22            crosstalk_1.2.1         digest_0.6.35          
[28] grid_4.3.1              leafem_0.2.3            base64enc_0.1-3        
[31] lifecycle_1.0.4         KernSmooth_2.23-21      proxy_0.4-27           
[34] glue_1.7.0              farver_2.1.1            codetools_0.2-19       
[37] stats4_4.3.1            e1071_1.7-14            colorspace_2.1-0       
[40] tools_4.3.1             htmltools_0.5.8.1
```

## Leafem
Similarly, when I use the example code from leafem with plainview version 0.2.1, I see this issue:
```
library(leaflet)
library(leafem)
library(plainview)

leaflet() %>%
  addProviderTiles("OpenStreetMap") %>%
  addRasterImage(poppendorf[[1]], project = TRUE, group = "poppendorf",
                 layerId = "poppendorf") %>%
  addImageQuery(poppendorf[[1]], project = TRUE,
                layerId = "poppendorf") %>%
  addLayersControl(overlayGroups = "poppendorf")
```
![image](https://github.com/r-spatial/mapview/assets/15910496/cbf2369b-5679-4103-a9d4-1903b02828b6)

with the following js errors

```
/s/46da16632800d364b…a-0.0.1/joda.js:131 Uncaught TypeError: layer.value.toFixed is not a function
 leafem: Failed to find window.data
```

**Comment by DavZim** [comment]
Maybe this is wrong here and instead should be moved to leafem, as joda is part of leafem and not mapview (cf https://github.com/r-spatial/leafem/blob/830d010f6087ba85bb71d7391d78db60dc8fef53/inst/htmlwidgets/lib/joda/joda.js#L131).

**Comment by tim-salabim** [comment]
No worries. I'll take a look soon

**Comment by tim-salabim** [comment]
Strange, works for me:

![image](https://github.com/r-spatial/mapview/assets/2826432/bbc456a8-39c9-4ca2-ad28-54694dd66143)

What browser are you using? I've tested in both Firefox and Chromium and it works in both (as it does in RStudio v. 2023.12.1 Build 402). Also tested under R 4.3.1 and 4.4.0. 

sessionInfo:

```r
> sessionInfo()
R version 4.4.0 Patched (2024-04-25 r86484)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 22.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=de_DE.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/Berlin
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] plainview_0.2.1 leafem_0.2.3    leaflet_2.2.2  

loaded via a namespace (and not attached):
 [1] jsonlite_1.8.8          jsonify_1.2.2           compiler_4.4.0         
 [4] Rcpp_1.0.12             jquerylib_0.1.4         scales_1.3.0           
 [7] png_0.1-8               fastmap_1.1.1           lattice_0.22-6         
[10] R6_2.5.1                classInt_0.4-10         sf_1.0-16              
[13] htmlwidgets_1.6.4       leaflet.providers_2.0.0 units_0.8-5            
[16] munsell_0.5.1           DBI_1.2.2               RColorBrewer_1.1-3     
[19] rlang_1.1.3             sp_2.1-4                terra_1.7-71           
[22] xfun_0.43               viridisLite_0.4.2       cli_3.6.2              
[25] magrittr_2.0.3          class_7.3-22            crosstalk_1.2.1        
[28] digest_0.6.35           grid_4.4.0              rstudioapi_0.16.0      
[31] colourvalues_0.3.9      base64enc_0.1-3         lifecycle_1.0.4        
[34] KernSmooth_2.23-22      proxy_0.4-27            glue_1.7.0             
[37] raster_3.6-26           farver_2.1.1            codetools_0.2-20       
[40] e1071_1.7-14            colorspace_2.1-0        tools_4.4.0            
[43] htmltools_0.5.8.1  
```

**Comment by DavZim** [comment]
I am working on a corporate installation of Posit Workbench, which I access from the lastest version of Chrome.

I also saw the following error in the console: `Refused to execute script from '.../viewhtml221db86a391847/lib/poppendorf_86590b-1/data_stars_stars2483fe.txt' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.`
Let me ask internally if this breaks the functionality somehow and if we can do something around it

**Comment by tim-salabim** [comment]
That does indeed look like the culprit, as `'.../viewhtml221db86a391847/lib/poppendorf_86590b-1/data_stars_stars2483fe.txt'` should be the file that contains the values being queried and displayed on hover

**Comment by DavZim** [comment]
interestingly enough, it works when I use it in a shiny app and only breaks in the viewer.
Anyways, nothing you can do about it. Thanks for looking into it though!
